### ISSUE TITLE
User 객체 생성

### ISSUE THREAD

**Issue by gnoesnooj** [class071/timotae#2]
### User 객체 생성
- 이름
- 나이
- 아이디
- 패스워드
- 이메일

**Comment by graygreat** [comment]
조금 더 자세히 적어주면 좋을듯 
유효성 검사 같은거

**Comment by gnoesnooj** [comment]
post 객체 할때도 그냥 기본만 하고 구현했어서 일단 User 객체 이슈에도 이렇게만 적어놨습니다

유효성 검사나 예외처리 같은거 post 객체에선 나중에 따로 branch 해서 pr 올리려고합니당

user 객체 할때는 영기가 편한대로 해도 될듯합니다
